name: crypto_nest
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  supabase_flutter: ^2.5.6
  url_launcher: ^6.3.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  country_picker: ^2.0.27
  image_picker: ^0.8.7+5
  cupertino_icons: ^1.0.5
  fl_chart: ^1.1.1
  shared_preferences: ^2.5.4
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
